//
// Generated file, do not edit! Created by nedtool 5.2 from DL_PDU.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __DL_PDU_M_H
#define __DL_PDU_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>DL_PDU.msg:21</tt> by nedtool.
 * <pre>
 * packet DL_PDU
 * {
 *     string data;
 *     int type;				 // 0: Data, 1 = Ack
 *     int source_address;
 *     int destination_address;
 * }
 * </pre>
 */
class DL_PDU : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string data;
    int type;
    int source_address;
    int destination_address;

  private:
    void copy(const DL_PDU& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DL_PDU&);

  public:
    DL_PDU(const char *name=nullptr, short kind=0);
    DL_PDU(const DL_PDU& other);
    virtual ~DL_PDU();
    DL_PDU& operator=(const DL_PDU& other);
    virtual DL_PDU *dup() const override {return new DL_PDU(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getData() const;
    virtual void setData(const char * data);
    virtual int getType() const;
    virtual void setType(int type);
    virtual int getSource_address() const;
    virtual void setSource_address(int source_address);
    virtual int getDestination_address() const;
    virtual void setDestination_address(int destination_address);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DL_PDU& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DL_PDU& obj) {obj.parsimUnpack(b);}


#endif // ifndef __DL_PDU_M_H

