//
// Generated file, do not edit! Created by nedtool 5.2 from msgpacket.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __MSGPACKET_M_H
#define __MSGPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>msgpacket.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * enum msgType
 * {
 * 
 *     Data = 1;
 *     Ack = 2;
 * }
 * </pre>
 */
enum msgType {
    Data = 1,
    Ack = 2
};

/**
 * Class generated from <tt>msgpacket.msg:25</tt> by nedtool.
 * <pre>
 * packet Msgpacket
 * {
 *     int id;
 *     int destination_address;
 *     int type \@enum(msgType);
 * }
 * </pre>
 */
class Msgpacket : public ::omnetpp::cPacket
{
  protected:
    int id;
    int destination_address;
    int type;

  private:
    void copy(const Msgpacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Msgpacket&);

  public:
    Msgpacket(const char *name=nullptr, short kind=0);
    Msgpacket(const Msgpacket& other);
    virtual ~Msgpacket();
    Msgpacket& operator=(const Msgpacket& other);
    virtual Msgpacket *dup() const override {return new Msgpacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getDestination_address() const;
    virtual void setDestination_address(int destination_address);
    virtual int getType() const;
    virtual void setType(int type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Msgpacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Msgpacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MSGPACKET_M_H

